### ISSUE TITLE
What's v2 module in both ssd.py and detection.py?

### ISSUE THREAD

**Issue by cnr0724** [sayakbanerjee1999/Single-Shot-Object-Detection-Updated#3]
```
Traceback (most recent call last):
  File "eval.py", line 16, in <module>
    from ssd import build_ssd
  File "/home/dnaplus/Downloads/ssd.pytorch/ssd.py", line 5, in <module>
    from layers import *
  File "/home/dnaplus/Downloads/ssd.pytorch/layers/__init__.py", line 1, in <module>
    from .functions import *
  File "/home/dnaplus/Downloads/ssd.pytorch/layers/functions/__init__.py", line 1, in <module>
    from .detection import Detect
  File "/home/dnaplus/Downloads/ssd.pytorch/layers/functions/detection.py", line 13, in <module>
    from data import v2 as cfg
ImportError: cannot import name 'v2'
```

Since there's no v2 module or class in data folder, the code is not runnable.....

**Comment by cnr0724** [comment]
Thanks for the code btw:)

**Comment by Lorisyy** [comment]
Same problem, could you @sayakbanerjee1999  please specify the version of your dependencies? 
Inconsistent version is a difficult problem, thanks a lot.

**Comment by sayakbanerjee1999** [comment]
Feel free to connect with me via LinkedIn
